DROP SCHEMA IF EXISTS `notes_keeper_db`;
CREATE SCHEMA `notes_keeper_db`;

USE `notes_keeper_db`;

DROP TABLE IF EXISTS `base_info`;
CREATE TABLE `base_info` (
	`Id`						INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Uuid`						VARCHAR(36) NOT NULL,
    `CreatedTimestamp`			TIMESTAMP NOT NULL,
    `ModificationTimeStamp`		TIMESTAMP
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
	`Id`						INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `UserName`					VARCHAR(50) NOT NULL,
    `Password`					VARCHAR(80) NOT NULL,
    `FirstName`					VARCHAR(50),
    `LastName`					VARCHAR(50),
    `AddressEmail`				VARCHAR(100) NOT NULL,
    CONSTRAINT `FK_UserId` FOREIGN KEY(`Id`) REFERENCES `base_info`(`Id`),
    CONSTRAINT `UQ_UserName` UNIQUE(`UserName`),
    CONSTRAINT `UQ_AddressEmail` UNIQUE(`AddressEmail`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `role`;
CREATE TABLE `role` (
	`Id`						INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `RoleName`					VARCHAR(10) NOT NULL,
    CONSTRAINT `FK_RoleId` FOREIGN KEY(`Id`) REFERENCES `base_info`(`Id`),
    CONSTRAINT `UQ_RoleName` UNIQUE (`RoleName`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `user_roles`;
CREATE TABLE `user_roles` (
	`UserId`					INT UNSIGNED NOT NULL,
    `RoleId`					INT UNSIGNED NOT NULL,
    PRIMARY KEY (`UserId`, `RoleId`),
    CONSTRAINT `FK_UserRolesUserId` FOREIGN KEY(`UserId`) REFERENCES `user`(`Id`),
    CONSTRAINT `FK_UserRolesRoleId` FOREIGN KEY(`RoleId`) REFERENCES role(`Id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `note`;
CREATE TABLE `note` (
	`Id`						INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Title`						VARCHAR(255) NOT NULL,
    `Note`						TEXT NOT NULL,
    `OwnerOfNoteId`				INT UNSIGNED NOT NULL,
    CONSTRAINT `FK_NoteId` FOREIGN KEY(`Id`) REFERENCES `base_info`(`Id`),
    CONSTRAINT `FK_OwnerOfNoteId` FOREIGN KEY(`OwnerOfNoteId`) REFERENCES `user`(`Id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;








